// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package books

import (
	"context"
)

const getAllUsers = `-- name: GetAllUsers :one
SELECT id, username, email, password, salt, refresh_token, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetAllUsers(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getAllUsers, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
